In [18]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

pd.set_option('display.max_rows', None)

Carregando as bases de dados

In [2]:
virus_core_dataset = pd.read_csv('C:/Users/kened/OneDrive/Desktop/Estudos/Lean/data/raw/virus_core.csv')
virus_core_dataset

,virus_id,name,family,genus,genome_type,strand,enveloped
0,1,SARS-CoV-2,NaN,Betacoronavirus,RNA,ssRNA(+),True
1,2,Influenza A virus,Orthomyxoviridae,NaN,rna,ssRNA(-),True
2,3,HIV-1,Retroviridae,Lentivirus,RNA,ssRNA-RT,True
3,4,Ebola virus,Filoviridae,Ebolavirus,RNA,ssRNA(-),True
4,5,Zika virus,NaN,Flavivirus,RNA,ssRNA(+),True
5,6,Dengue virus,Flaviviridae,NaN,RNA,ssRNA(+),True
6,7,Rabies virus,Rhabdoviridae,Lyssavirus,RNA,ssRNA(-),True
7,8,Hepatitis B virus,Hepadnaviridae,Orthohepadnavirus,DNA,partially dsDNA,True
8,9,Adenovirus,Adenoviridae,Mastadenovirus,DNA,dsDNA,False
9,10,Human papillomavirus,Papillomaviridae,Alphapapillomavirus,DNA,dsDNA,False
10,11,MERS-CoV,NaN,Betacoronavirus,RNA,ssRNA(+),True
11,12,HCoV-OC43,Coronaviridae,Betacoronavirus,RNA,ssRNA(+),True
12,13,HCoV-229E,Coronaviridae,Alphacoronavirus,RNA,ssRNA(+),True
13,14,Norovirus,Caliciviridae,Norovirus,RNA,ssRNA(+),False
14,15,Rotavirus,Reoviridae,Rotavirus,RNA,dsRNA,False
15,16,Marburg virus,Filoviridae,Marburgvirus,RNA,ssRNA(-),True
16,17,Lassa virus,Arenaviridae,Mammarenavirus,RNA,ssRNA,True
17,18,Hantavirus,Hantaviridae,NaN,RNA,ssRNA(-),True
18,19,Yellow fever virus,NaN,NaN,RNA,ssRNA(+),True
19,20,West Nile virus,Flaviviridae,Flavivirus,RNA,ssRNA(+),True
20,21,Japanese encephalitis virus,Flaviviridae,Flavivirus,RNA,ssRNA(+),True
21,22,Measles virus,Paramyxoviridae,Morbillivirus,RNA,ssRNA(-),True
22,23,Mumps virus,NaN,Orthorubulavirus,RNA,ssRNA(-),True
23,24,Respiratory syncytial virus,Pneumoviridae,Orthopneumovirus,RNA,ssRNA(-),True
24,25,Smallpox virus,Poxviridae,Orthopoxvirus,DNA,dsDNA,True
25,26,Monkeypox virus,Poxviridae,Orthopoxvirus,Rna,dsDNA,True
26,27,Varicella-zoster virus,Herpesviridae,Varicellovirus,DNA,dsDNA,True
27,28,Herpes simplex virus 1,Herpesviridae,Simplexvirus,DNA,dsDNA,True
28,29,Herpes simplex virus 2,Herpesviridae,Simplexvirus,DNA,dsDNA,True
29,30,Cucurbit vein yellowing-associated varicosavirus,Unknown,Unknown,Unknown,Unknown,NaN
30,31,Aeromonas phage Aero_H33,Unknown,Unknown,Unknown,Unknown,NaN
31,32,Salmonella Siphovirus,Unknown,Unknown,Unknown,Unknown,NaN
32,33,Klebsiella phage vB_GCMC-1,Unknown,Unknown,Unknown,Unknown,NaN
33,34,Escherichia phage vB-EcoM-Eg05,Unknown,Unknown,Unknown,Unknown,NaN
34,35,Escherichia phage ECP2402,Unknown,Unknown,Unknown,Unknown,NaN
35,36,Pseudomonas phage vB_PaeA-38F,Unknown,Unknown,Unknown,Unknown,NaN
36,37,Colletotrichum-associated mitovirus 1,Unknown,Unknown,Unknown,Unknown,NaN
37,38,Colletotrichum tropicale botourmia-like virus,Unknown,Unknown,Unknown,Unknown,NaN
38,39,Colletotrichum queenslandicum fusarivirus 1,Unknown,Unknown,Unknown,Unknown,NaN
39,40,Colletotrichum plurivorum mitovirus 1,Unknown,Unknown,Unknown,Unknown,NaN
40,41,Escherichia phage ev_rybdy6,Unknown,Unknown,Unknown,Unknown,NaN
41,42,Escherichia phage ev_rybdy2,Unknown,Unknown,Unknown,Unknown,NaN
42,43,Escherichia phage ev_rybdy1,Unknown,Unknown,Unknown,Unknown,NaN
43,44,Klebsiella phage kv_tblp7,Unknown,Unknown,Unknown,Unknown,NaN
44,45,Klebsiella phage kv_tblp6,Unknown,Unknown,Unknown,Unknown,NaN
45,46,Klebsiella phage kv_tblp4,Unknown,Unknown,Unknown,Unknown,NaN
46,47,Klebsiella phage kv_tblp3,Unknown,Unknown,Unknown,Unknown,NaN
47,48,Klebsiella phage kv_tblp1,Unknown,Unknown,Unknown,Unknown,NaN
48,49,Staphylococcus phage sv_nwjns7,Unknown,Unknown,Unknown,Unknown,NaN
49,50,Staphylococcus phage sv_nwjns5,NaN,Unknown,Unknown,Unknown,NaN
50,51,Staphylococcus phage sv_nwjns4,Unknown,Unknown,Unknown,Unknown,NaN
51,52,Escherichia phage CFT073_Phlampion,Unknown,Unknown,Unknown,Unknown,NaN
52,53,Escherichia phage CFT073_Phlash,Unknown,Unknown,Unknown,Unknown,NaN
53,54,Mardivirus gallidalpha 2,Unknown,Unknown,Unknown,Unknown,NaN
54,55,Arthrobacter phage Vinye,NaN,Unknown,Unknown,Unknown,NaN
55,56,Arthrobacter phage Studio,Unknown,Unknown,Unknown,Unknown,NaN
56,57,Arthrobacter phage PoeMe,Unknown,Unknown,Unknown,Unknown,NaN
57,58,Arthrobacter phage Onestar,Unknown,Unknown,Unknown,Unknown,NaN
58,59,Arthrobacter phage Mireles,Unknown,Unknown,Unknown,Unknown,NaN
59,60,Mycobacterium phage LordVader,Unknown,Unknown,Unknown,Unknown,NaN
60,61,Arthrobacter phage LastNadiia,Unknown,Unknown,Unknown,Unknown,NaN
61,62,Microbacterium phage Kamdara,Unknown,Unknown,Unknown,Unknown,NaN
62,63,Arthrobacter phage GalaxyEater,Unknown,Unknown,Unknown,Unknown,NaN
63,64,Arthrobacter phage ERHickory,Unknown,Unknown,Unknown,Unknown,NaN
64,65,Arthrobacter phage Ellewin,Unknown,Unknown,Unknown,Unknown,NaN
65,66,Arthrobacter phage Divya,Unknown,Unknown,Unknown,Unknown,NaN
66,67,Mycobacterium phage Beanstalk,Unknown,Unknown,Unknown,Unknown,NaN
67,68,Arthrobacter phage Amphitrite,Unknown,Unknown,Unknown,Unknown,NaN
68,69,Arthrobacter phage Agamotto,Unknown,Unknown,Unknown,Unknown,NaN
69,70,Klebsiella phage Kp_AHMU1,Unknown,Unknown,Unknown,Unknown,NaN
70,3,HIV-1,Retroviridae,Lentivirus,RNA,ssRNA-RT,True
71,16,Marburg virus,Filoviridae,Marburgvirus,RNA,ssRNA(-),True
72,41,Escherichia phage ev_rybdy6,Unknown,Unknown,Unknown,Unknown,NaN

In [3]:
virus_epidemiology_dataset = pd.read_csv('C:/Users/kened/OneDrive/Desktop/Estudos/Lean/data/raw/virus_epidemiology.csv')
virus_epidemiology_dataset

    virus_id   transmission  mortality      r0    host
0          1       airborne       2.00    2.50   human
1          2       airborne       0.10    1.30   human
2          3  bodily fluids      80.00    2.00   human
3          4       Airborne        NaN    1.80   human
4          5         vector       0.01    3.00   human
5          6         vector     150.00    4.00   human
6          7    animal bite      99.00    0.50  animal
7          8       airborne       4.10    1.59     NaN
8          9         vector       0.23  500.00   human
9         10         vector        NaN    2.99  animal
10        11       airborne       1.56    3.46  animal
11        12         vector       6.10    2.06   human
12        13  bodily fluids      -5.00    2.75    both
13        14         vector       5.05    2.31     NaN
14        15        contact       2.70    2.92   human
15        16        contact        NaN    1.18    both
16        17        contact       9.80    3.19  animal
17        18        contact       0.45    2.76    both
18        19        vectorr       5.16    0.99  animal
19        20        contact       7.99    0.53  animal
20        21  bodily fluids       6.53   -1.20     NaN
21        22        contact       1.59    2.29   human
22        23        contact       9.84    1.98  animal
23        24       airborne       5.07    1.52    both
24        25  bodily fluids       0.85    1.50  animal
25        26       airborne       2.12    2.97  animal
26        27         vector       6.48    2.20  animal
27        28        contact       0.56    1.83   human
28        29  bodily fluids       7.82    1.88   human
29        30         vector       7.72    2.20  animal
30        31        contact      99.90    2.36     NaN
31        32        contact       1.99    3.30  animal
32        33        contact       8.43    1.70  animal
33        34       airborne       6.83    2.71  animal
34        35        contact       2.95    3.29  animal
35        36      air borne       6.71    2.05    both
36        37  bodily fluids       9.55    0.51    both
37        38         vector       7.36    0.95  animal
38        39         vector       8.33    0.92    both
39        40       airborne       6.95    3.43    both
40        41         vector       9.13    1.18   human
41        42       airborne       7.00    3.35     NaN
42        43         vector       5.91    1.43    both
43        44  bodily fluids       5.29    2.67    both
44        45        contact       2.65    0.98    both
45        46        contact       4.75    1.23   human
46        47  bodily fluids       8.77    1.34   human
47        48         vector       4.29    1.35    both
48        49         vector       2.60    1.55   human
49        50  bodily fluids       8.32    2.17   human
50        51       airborne       9.26    0.65    both
51        52         vector       9.44    2.90  animal
52        53         vector       9.88    3.03   human
53        54       airborne       0.57    2.82    both
54        55  bodily fluids       7.73    1.58    both
55        56         vector       2.64    1.67    both
56        57         vector       1.48    3.06     NaN
57        58         vector       6.90    3.47    both
58        59       airborne       0.72    2.26    both
59        60         vector       9.65    0.53   human
60        61  bodily fluids       7.68    2.75    both
61        62  bodily fluids       9.15    2.95    both
62        63         vector       1.37    1.70    both
63        64         vector       3.76    2.55  animal
64        65  bodily fluids       6.30    2.52    both
65        66       airborne       3.92    1.32    both
66        67        contact       1.20    1.21    both
67        68  bodily fluids       3.41    1.03    both
68        69       airborne       4.29    1.19  animal
69        70  bodily fluids       7.25    0.75  animal
70         8       airborne       4.10    1.59     NaN
71        34       airborne       6.83    2.71  animal

In [4]:
virus_target_dataset = pd.read_csv('C:/Users/kened/OneDrive/Desktop/Estudos/Lean/data/raw/virus_target.csv')
virus_target_dataset

    virus_id risk_category
0          1           low
1          2           low
2          3          high
3          4        medium
4          5           low
5          6           low
6          7          high
7          8           low
8          9           low
9         10        medium
10        11           low
11        12        medium
12        13           low
13        14        medium
14        15           low
15        16           low
16        17        medium
17        18           low
18        19        medium
19        20        medium
20        21        medium
21        22           low
22        23        medium
23        24        medium
24        25           low
25        26           low
26        27        medium
27        28           low
28        29        medium
29        30        medium
30        31           low
31        32           low
32        33        medium
33        34        medium
34        35           low
35        36        medium
36        37        medium
37        38        medium
38        39        medium
39        40        medium
40        41        medium
41        42        medium
42        43        medium
43        44        medium
44        45           low
45        46           low
46        47        medium
47        48           low
48        49           low
49        50        medium
50        51        medium
51        52        medium
52        53        medium
53        54           low
54        55        medium
55        56           low
56        57           low
57        58        medium
58        59           low
59        60        medium
60        61        medium
61        62        medium
62        63           low
63        64           low
64        65        medium
65        66           low
66        67           low
67        68           low
68        69           low
69        70        medium

primeiro vamos verificar se há registros duplicados nos datasets

In [5]:
print('shapes:', virus_core_dataset.shape, virus_epidemiology_dataset.shape, virus_target_dataset.shape)
print('registros duplicados em virus_core:', virus_core_dataset['virus_id'].duplicated().sum())
print('registros duplicados em virus_epidemiology:', virus_epidemiology_dataset['virus_id'].duplicated().sum())
print('registros duplicados em virus_target:', virus_target_dataset['virus_id'].duplicated().sum())

shapes: (73, 7) (72, 5) (70, 2)
registros duplicados em virus_core: 3
registros duplicados em virus_epidemiology: 2
registros duplicados em virus_target: 0

Checando melhor os registros para verificar se são exatamente os mesmos

In [6]:
display(virus_core_dataset[virus_core_dataset['virus_id'].duplicated(keep=False)])
display(virus_epidemiology_dataset[virus_epidemiology_dataset['virus_id'].duplicated(keep=False)])

,virus_id,name,family,genus,genome_type,strand,enveloped
2,3,HIV-1,Retroviridae,Lentivirus,RNA,ssRNA-RT,True
15,16,Marburg virus,Filoviridae,Marburgvirus,RNA,ssRNA(-),True
40,41,Escherichia phage ev_rybdy6,Unknown,Unknown,Unknown,Unknown,NaN
70,3,HIV-1,Retroviridae,Lentivirus,RNA,ssRNA-RT,True
71,16,Marburg virus,Filoviridae,Marburgvirus,RNA,ssRNA(-),True
72,41,Escherichia phage ev_rybdy6,Unknown,Unknown,Unknown,Unknown,NaN

    virus_id transmission  mortality    r0    host
7          8     airborne       4.10  1.59     NaN
33        34     airborne       6.83  2.71  animal
70         8     airborne       4.10  1.59     NaN
71        34     airborne       6.83  2.71  animal

In [7]:
virus_core_dataset = virus_core_dataset.drop_duplicates()
virus_epidemiology_dataset = virus_epidemiology_dataset.drop_duplicates()

print('shapes:', virus_core_dataset.shape, virus_epidemiology_dataset.shape, virus_target_dataset.shape)
print('registros duplicados em virus_core:', virus_core_dataset['virus_id'].duplicated().sum())
print('registros duplicados em virus_epidemiology:', virus_epidemiology_dataset['virus_id'].duplicated().sum())

shapes: (70, 7) (70, 5) (70, 2)
registros duplicados em virus_core: 0
registros duplicados em virus_epidemiology: 0

Identifiquei 3 registros duplicados em virus_core e 2 em virus_epidemiology. Ao inspecionar as linhas, percebi que são duplicatas exatas, sem conflito de valores.
Optei por remover com drop_duplicates() mantendo a primeira ocorrência pois manter duplicados poderia enviesar o modelo dando peso indevido a certos vírus.

In [8]:
dataset_parcial = pd.merge(virus_core_dataset,virus_epidemiology_dataset,on='virus_id',how='inner')
dataset_parcial

,virus_id,name,family,genus,genome_type,strand,enveloped,transmission,mortality,r0,host
0,1,SARS-CoV-2,NaN,Betacoronavirus,RNA,ssRNA(+),True,airborne,2.00,2.50,human
1,2,Influenza A virus,Orthomyxoviridae,NaN,rna,ssRNA(-),True,airborne,0.10,1.30,human
2,3,HIV-1,Retroviridae,Lentivirus,RNA,ssRNA-RT,True,bodily fluids,80.00,2.00,human
3,4,Ebola virus,Filoviridae,Ebolavirus,RNA,ssRNA(-),True,Airborne,NaN,1.80,human
4,5,Zika virus,NaN,Flavivirus,RNA,ssRNA(+),True,vector,0.01,3.00,human
5,6,Dengue virus,Flaviviridae,NaN,RNA,ssRNA(+),True,vector,150.00,4.00,human
6,7,Rabies virus,Rhabdoviridae,Lyssavirus,RNA,ssRNA(-),True,animal bite,99.00,0.50,animal
7,8,Hepatitis B virus,Hepadnaviridae,Orthohepadnavirus,DNA,partially dsDNA,True,airborne,4.10,1.59,NaN
8,9,Adenovirus,Adenoviridae,Mastadenovirus,DNA,dsDNA,False,vector,0.23,500.00,human
9,10,Human papillomavirus,Papillomaviridae,Alphapapillomavirus,DNA,dsDNA,False,vector,NaN,2.99,animal
10,11,MERS-CoV,NaN,Betacoronavirus,RNA,ssRNA(+),True,airborne,1.56,3.46,animal
11,12,HCoV-OC43,Coronaviridae,Betacoronavirus,RNA,ssRNA(+),True,vector,6.10,2.06,human
12,13,HCoV-229E,Coronaviridae,Alphacoronavirus,RNA,ssRNA(+),True,bodily fluids,-5.00,2.75,both
13,14,Norovirus,Caliciviridae,Norovirus,RNA,ssRNA(+),False,vector,5.05,2.31,NaN
14,15,Rotavirus,Reoviridae,Rotavirus,RNA,dsRNA,False,contact,2.70,2.92,human
15,16,Marburg virus,Filoviridae,Marburgvirus,RNA,ssRNA(-),True,contact,NaN,1.18,both
16,17,Lassa virus,Arenaviridae,Mammarenavirus,RNA,ssRNA,True,contact,9.80,3.19,animal
17,18,Hantavirus,Hantaviridae,NaN,RNA,ssRNA(-),True,contact,0.45,2.76,both
18,19,Yellow fever virus,NaN,NaN,RNA,ssRNA(+),True,vectorr,5.16,0.99,animal
19,20,West Nile virus,Flaviviridae,Flavivirus,RNA,ssRNA(+),True,contact,7.99,0.53,animal
20,21,Japanese encephalitis virus,Flaviviridae,Flavivirus,RNA,ssRNA(+),True,bodily fluids,6.53,-1.20,NaN
21,22,Measles virus,Paramyxoviridae,Morbillivirus,RNA,ssRNA(-),True,contact,1.59,2.29,human
22,23,Mumps virus,NaN,Orthorubulavirus,RNA,ssRNA(-),True,contact,9.84,1.98,animal
23,24,Respiratory syncytial virus,Pneumoviridae,Orthopneumovirus,RNA,ssRNA(-),True,airborne,5.07,1.52,both
24,25,Smallpox virus,Poxviridae,Orthopoxvirus,DNA,dsDNA,True,bodily fluids,0.85,1.50,animal
25,26,Monkeypox virus,Poxviridae,Orthopoxvirus,Rna,dsDNA,True,airborne,2.12,2.97,animal
26,27,Varicella-zoster virus,Herpesviridae,Varicellovirus,DNA,dsDNA,True,vector,6.48,2.20,animal
27,28,Herpes simplex virus 1,Herpesviridae,Simplexvirus,DNA,dsDNA,True,contact,0.56,1.83,human
28,29,Herpes simplex virus 2,Herpesviridae,Simplexvirus,DNA,dsDNA,True,bodily fluids,7.82,1.88,human
29,30,Cucurbit vein yellowing-associated varicosavirus,Unknown,Unknown,Unknown,Unknown,NaN,vector,7.72,2.20,animal
30,31,Aeromonas phage Aero_H33,Unknown,Unknown,Unknown,Unknown,NaN,contact,99.90,2.36,NaN
31,32,Salmonella Siphovirus,Unknown,Unknown,Unknown,Unknown,NaN,contact,1.99,3.30,animal
32,33,Klebsiella phage vB_GCMC-1,Unknown,Unknown,Unknown,Unknown,NaN,contact,8.43,1.70,animal
33,34,Escherichia phage vB-EcoM-Eg05,Unknown,Unknown,Unknown,Unknown,NaN,airborne,6.83,2.71,animal
34,35,Escherichia phage ECP2402,Unknown,Unknown,Unknown,Unknown,NaN,contact,2.95,3.29,animal
35,36,Pseudomonas phage vB_PaeA-38F,Unknown,Unknown,Unknown,Unknown,NaN,air borne,6.71,2.05,both
36,37,Colletotrichum-associated mitovirus 1,Unknown,Unknown,Unknown,Unknown,NaN,bodily fluids,9.55,0.51,both
37,38,Colletotrichum tropicale botourmia-like virus,Unknown,Unknown,Unknown,Unknown,NaN,vector,7.36,0.95,animal
38,39,Colletotrichum queenslandicum fusarivirus 1,Unknown,Unknown,Unknown,Unknown,NaN,vector,8.33,0.92,both
39,40,Colletotrichum plurivorum mitovirus 1,Unknown,Unknown,Unknown,Unknown,NaN,airborne,6.95,3.43,both
40,41,Escherichia phage ev_rybdy6,Unknown,Unknown,Unknown,Unknown,NaN,vector,9.13,1.18,human
41,42,Escherichia phage ev_rybdy2,Unknown,Unknown,Unknown,Unknown,NaN,airborne,7.00,3.35,NaN
42,43,Escherichia phage ev_rybdy1,Unknown,Unknown,Unknown,Unknown,NaN,vector,5.91,1.43,both
43,44,Klebsiella phage kv_tblp7,Unknown,Unknown,Unknown,Unknown,NaN,bodily fluids,5.29,2.67,both
44,45,Klebsiella phage kv_tblp6,Unknown,Unknown,Unknown,Unknown,NaN,contact,2.65,0.98,both
45,46,Klebsiella phage kv_tblp4,Unknown,Unknown,Unknown,Unknown,NaN,contact,4.75,1.23,human
46,47,Klebsiella phage kv_tblp3,Unknown,Unknown,Unknown,Unknown,NaN,bodily fluids,8.77,1.34,human
47,48,Klebsiella phage kv_tblp1,Unknown,Unknown,Unknown,Unknown,NaN,vector,4.29,1.35,both
48,49,Staphylococcus phage sv_nwjns7,Unknown,Unknown,Unknown,Unknown,NaN,vector,2.60,1.55,human
49,50,Staphylococcus phage sv_nwjns5,NaN,Unknown,Unknown,Unknown,NaN,bodily fluids,8.32,2.17,human
50,51,Staphylococcus phage sv_nwjns4,Unknown,Unknown,Unknown,Unknown,NaN,airborne,9.26,0.65,both
51,52,Escherichia phage CFT073_Phlampion,Unknown,Unknown,Unknown,Unknown,NaN,vector,9.44,2.90,animal
52,53,Escherichia phage CFT073_Phlash,Unknown,Unknown,Unknown,Unknown,NaN,vector,9.88,3.03,human
53,54,Mardivirus gallidalpha 2,Unknown,Unknown,Unknown,Unknown,NaN,airborne,0.57,2.82,both
54,55,Arthrobacter phage Vinye,NaN,Unknown,Unknown,Unknown,NaN,bodily fluids,7.73,1.58,both
55,56,Arthrobacter phage Studio,Unknown,Unknown,Unknown,Unknown,NaN,vector,2.64,1.67,both
56,57,Arthrobacter phage PoeMe,Unknown,Unknown,Unknown,Unknown,NaN,vector,1.48,3.06,NaN
57,58,Arthrobacter phage Onestar,Unknown,Unknown,Unknown,Unknown,NaN,vector,6.90,3.47,both
58,59,Arthrobacter phage Mireles,Unknown,Unknown,Unknown,Unknown,NaN,airborne,0.72,2.26,both
59,60,Mycobacterium phage LordVader,Unknown,Unknown,Unknown,Unknown,NaN,vector,9.65,0.53,human
60,61,Arthrobacter phage LastNadiia,Unknown,Unknown,Unknown,Unknown,NaN,bodily fluids,7.68,2.75,both
61,62,Microbacterium phage Kamdara,Unknown,Unknown,Unknown,Unknown,NaN,bodily fluids,9.15,2.95,both
62,63,Arthrobacter phage GalaxyEater,Unknown,Unknown,Unknown,Unknown,NaN,vector,1.37,1.70,both
63,64,Arthrobacter phage ERHickory,Unknown,Unknown,Unknown,Unknown,NaN,vector,3.76,2.55,animal
64,65,Arthrobacter phage Ellewin,Unknown,Unknown,Unknown,Unknown,NaN,bodily fluids,6.30,2.52,both
65,66,Arthrobacter phage Divya,Unknown,Unknown,Unknown,Unknown,NaN,airborne,3.92,1.32,both
66,67,Mycobacterium phage Beanstalk,Unknown,Unknown,Unknown,Unknown,NaN,contact,1.20,1.21,both
67,68,Arthrobacter phage Amphitrite,Unknown,Unknown,Unknown,Unknown,NaN,bodily fluids,3.41,1.03,both
68,69,Arthrobacter phage Agamotto,Unknown,Unknown,Unknown,Unknown,NaN,airborne,4.29,1.19,animal
69,70,Klebsiella phage Kp_AHMU1,Unknown,Unknown,Unknown,Unknown,NaN,bodily fluids,7.25,0.75,animal

In [9]:
dataset_full = pd.merge(dataset_parcial,virus_target_dataset,on='virus_id',how='inner')
dataset_full

,virus_id,name,family,genus,genome_type,strand,enveloped,transmission,mortality,r0,host,risk_category
0,1,SARS-CoV-2,NaN,Betacoronavirus,RNA,ssRNA(+),True,airborne,2.00,2.50,human,low
1,2,Influenza A virus,Orthomyxoviridae,NaN,rna,ssRNA(-),True,airborne,0.10,1.30,human,low
2,3,HIV-1,Retroviridae,Lentivirus,RNA,ssRNA-RT,True,bodily fluids,80.00,2.00,human,high
3,4,Ebola virus,Filoviridae,Ebolavirus,RNA,ssRNA(-),True,Airborne,NaN,1.80,human,medium
4,5,Zika virus,NaN,Flavivirus,RNA,ssRNA(+),True,vector,0.01,3.00,human,low
5,6,Dengue virus,Flaviviridae,NaN,RNA,ssRNA(+),True,vector,150.00,4.00,human,low
6,7,Rabies virus,Rhabdoviridae,Lyssavirus,RNA,ssRNA(-),True,animal bite,99.00,0.50,animal,high
7,8,Hepatitis B virus,Hepadnaviridae,Orthohepadnavirus,DNA,partially dsDNA,True,airborne,4.10,1.59,NaN,low
8,9,Adenovirus,Adenoviridae,Mastadenovirus,DNA,dsDNA,False,vector,0.23,500.00,human,low
9,10,Human papillomavirus,Papillomaviridae,Alphapapillomavirus,DNA,dsDNA,False,vector,NaN,2.99,animal,medium
10,11,MERS-CoV,NaN,Betacoronavirus,RNA,ssRNA(+),True,airborne,1.56,3.46,animal,low
11,12,HCoV-OC43,Coronaviridae,Betacoronavirus,RNA,ssRNA(+),True,vector,6.10,2.06,human,medium
12,13,HCoV-229E,Coronaviridae,Alphacoronavirus,RNA,ssRNA(+),True,bodily fluids,-5.00,2.75,both,low
13,14,Norovirus,Caliciviridae,Norovirus,RNA,ssRNA(+),False,vector,5.05,2.31,NaN,medium
14,15,Rotavirus,Reoviridae,Rotavirus,RNA,dsRNA,False,contact,2.70,2.92,human,low
15,16,Marburg virus,Filoviridae,Marburgvirus,RNA,ssRNA(-),True,contact,NaN,1.18,both,low
16,17,Lassa virus,Arenaviridae,Mammarenavirus,RNA,ssRNA,True,contact,9.80,3.19,animal,medium
17,18,Hantavirus,Hantaviridae,NaN,RNA,ssRNA(-),True,contact,0.45,2.76,both,low
18,19,Yellow fever virus,NaN,NaN,RNA,ssRNA(+),True,vectorr,5.16,0.99,animal,medium
19,20,West Nile virus,Flaviviridae,Flavivirus,RNA,ssRNA(+),True,contact,7.99,0.53,animal,medium
20,21,Japanese encephalitis virus,Flaviviridae,Flavivirus,RNA,ssRNA(+),True,bodily fluids,6.53,-1.20,NaN,medium
21,22,Measles virus,Paramyxoviridae,Morbillivirus,RNA,ssRNA(-),True,contact,1.59,2.29,human,low
22,23,Mumps virus,NaN,Orthorubulavirus,RNA,ssRNA(-),True,contact,9.84,1.98,animal,medium
23,24,Respiratory syncytial virus,Pneumoviridae,Orthopneumovirus,RNA,ssRNA(-),True,airborne,5.07,1.52,both,medium
24,25,Smallpox virus,Poxviridae,Orthopoxvirus,DNA,dsDNA,True,bodily fluids,0.85,1.50,animal,low
25,26,Monkeypox virus,Poxviridae,Orthopoxvirus,Rna,dsDNA,True,airborne,2.12,2.97,animal,low
26,27,Varicella-zoster virus,Herpesviridae,Varicellovirus,DNA,dsDNA,True,vector,6.48,2.20,animal,medium
27,28,Herpes simplex virus 1,Herpesviridae,Simplexvirus,DNA,dsDNA,True,contact,0.56,1.83,human,low
28,29,Herpes simplex virus 2,Herpesviridae,Simplexvirus,DNA,dsDNA,True,bodily fluids,7.82,1.88,human,medium
29,30,Cucurbit vein yellowing-associated varicosavirus,Unknown,Unknown,Unknown,Unknown,NaN,vector,7.72,2.20,animal,medium
30,31,Aeromonas phage Aero_H33,Unknown,Unknown,Unknown,Unknown,NaN,contact,99.90,2.36,NaN,low
31,32,Salmonella Siphovirus,Unknown,Unknown,Unknown,Unknown,NaN,contact,1.99,3.30,animal,low
32,33,Klebsiella phage vB_GCMC-1,Unknown,Unknown,Unknown,Unknown,NaN,contact,8.43,1.70,animal,medium
33,34,Escherichia phage vB-EcoM-Eg05,Unknown,Unknown,Unknown,Unknown,NaN,airborne,6.83,2.71,animal,medium
34,35,Escherichia phage ECP2402,Unknown,Unknown,Unknown,Unknown,NaN,contact,2.95,3.29,animal,low
35,36,Pseudomonas phage vB_PaeA-38F,Unknown,Unknown,Unknown,Unknown,NaN,air borne,6.71,2.05,both,medium
36,37,Colletotrichum-associated mitovirus 1,Unknown,Unknown,Unknown,Unknown,NaN,bodily fluids,9.55,0.51,both,medium
37,38,Colletotrichum tropicale botourmia-like virus,Unknown,Unknown,Unknown,Unknown,NaN,vector,7.36,0.95,animal,medium
38,39,Colletotrichum queenslandicum fusarivirus 1,Unknown,Unknown,Unknown,Unknown,NaN,vector,8.33,0.92,both,medium
39,40,Colletotrichum plurivorum mitovirus 1,Unknown,Unknown,Unknown,Unknown,NaN,airborne,6.95,3.43,both,medium
40,41,Escherichia phage ev_rybdy6,Unknown,Unknown,Unknown,Unknown,NaN,vector,9.13,1.18,human,medium
41,42,Escherichia phage ev_rybdy2,Unknown,Unknown,Unknown,Unknown,NaN,airborne,7.00,3.35,NaN,medium
42,43,Escherichia phage ev_rybdy1,Unknown,Unknown,Unknown,Unknown,NaN,vector,5.91,1.43,both,medium
43,44,Klebsiella phage kv_tblp7,Unknown,Unknown,Unknown,Unknown,NaN,bodily fluids,5.29,2.67,both,medium
44,45,Klebsiella phage kv_tblp6,Unknown,Unknown,Unknown,Unknown,NaN,contact,2.65,0.98,both,low
45,46,Klebsiella phage kv_tblp4,Unknown,Unknown,Unknown,Unknown,NaN,contact,4.75,1.23,human,low
46,47,Klebsiella phage kv_tblp3,Unknown,Unknown,Unknown,Unknown,NaN,bodily fluids,8.77,1.34,human,medium
47,48,Klebsiella phage kv_tblp1,Unknown,Unknown,Unknown,Unknown,NaN,vector,4.29,1.35,both,low
48,49,Staphylococcus phage sv_nwjns7,Unknown,Unknown,Unknown,Unknown,NaN,vector,2.60,1.55,human,low
49,50,Staphylococcus phage sv_nwjns5,NaN,Unknown,Unknown,Unknown,NaN,bodily fluids,8.32,2.17,human,medium
50,51,Staphylococcus phage sv_nwjns4,Unknown,Unknown,Unknown,Unknown,NaN,airborne,9.26,0.65,both,medium
51,52,Escherichia phage CFT073_Phlampion,Unknown,Unknown,Unknown,Unknown,NaN,vector,9.44,2.90,animal,medium
52,53,Escherichia phage CFT073_Phlash,Unknown,Unknown,Unknown,Unknown,NaN,vector,9.88,3.03,human,medium
53,54,Mardivirus gallidalpha 2,Unknown,Unknown,Unknown,Unknown,NaN,airborne,0.57,2.82,both,low
54,55,Arthrobacter phage Vinye,NaN,Unknown,Unknown,Unknown,NaN,bodily fluids,7.73,1.58,both,medium
55,56,Arthrobacter phage Studio,Unknown,Unknown,Unknown,Unknown,NaN,vector,2.64,1.67,both,low
56,57,Arthrobacter phage PoeMe,Unknown,Unknown,Unknown,Unknown,NaN,vector,1.48,3.06,NaN,low
57,58,Arthrobacter phage Onestar,Unknown,Unknown,Unknown,Unknown,NaN,vector,6.90,3.47,both,medium
58,59,Arthrobacter phage Mireles,Unknown,Unknown,Unknown,Unknown,NaN,airborne,0.72,2.26,both,low
59,60,Mycobacterium phage LordVader,Unknown,Unknown,Unknown,Unknown,NaN,vector,9.65,0.53,human,medium
60,61,Arthrobacter phage LastNadiia,Unknown,Unknown,Unknown,Unknown,NaN,bodily fluids,7.68,2.75,both,medium
61,62,Microbacterium phage Kamdara,Unknown,Unknown,Unknown,Unknown,NaN,bodily fluids,9.15,2.95,both,medium
62,63,Arthrobacter phage GalaxyEater,Unknown,Unknown,Unknown,Unknown,NaN,vector,1.37,1.70,both,low
63,64,Arthrobacter phage ERHickory,Unknown,Unknown,Unknown,Unknown,NaN,vector,3.76,2.55,animal,low
64,65,Arthrobacter phage Ellewin,Unknown,Unknown,Unknown,Unknown,NaN,bodily fluids,6.30,2.52,both,medium
65,66,Arthrobacter phage Divya,Unknown,Unknown,Unknown,Unknown,NaN,airborne,3.92,1.32,both,low
66,67,Mycobacterium phage Beanstalk,Unknown,Unknown,Unknown,Unknown,NaN,contact,1.20,1.21,both,low
67,68,Arthrobacter phage Amphitrite,Unknown,Unknown,Unknown,Unknown,NaN,bodily fluids,3.41,1.03,both,low
68,69,Arthrobacter phage Agamotto,Unknown,Unknown,Unknown,Unknown,NaN,airborne,4.29,1.19,animal,low
69,70,Klebsiella phage Kp_AHMU1,Unknown,Unknown,Unknown,Unknown,NaN,bodily fluids,7.25,0.75,animal,medium

Juntei os datasets pela chave virus_id para ter o panorâma geral dos dados em um só dataframe, agora o próximo passo é verificar 
valores ausentes,em quais colunas,estatística descritiva,Cardinalidade,tipos de dados etc

In [10]:
dataset_full.describe()

        virus_id   mortality          r0
count  70.000000   67.000000   70.000000
mean   35.500000   11.076716    9.105857
std    20.351085   25.440637   59.531158
min     1.000000   -5.000000   -1.200000
25%    18.250000    2.360000    1.305000
50%    35.500000    5.910000    2.025000
75%    52.750000    8.155000    2.805000
max    70.000000  150.000000  500.000000

In [11]:
dataset_full.isnull().sum()

virus_id          0
name              0
family            7
genus             4
genome_type       0
strand            0
enveloped        41
transmission      0
mortality         3
r0                0
host              6
risk_category     0
dtype: int64

In [12]:
dataset_full.dtypes

virus_id           int64
name              object
family            object
genus             object
genome_type       object
strand            object
enveloped         object
transmission      object
mortality        float64
r0               float64
host              object
risk_category     object
dtype: object

In [13]:
dataset_full.nunique()

virus_id         70
name             70
family           18
genus            20
genome_type       6
strand            8
enveloped         2
transmission      8
mortality        66
r0               65
host              3
risk_category     3
dtype: int64

In [20]:
for var in ['genome_type', 'strand', 'enveloped', 'transmission']:
    print(dataset_full[var].value_counts(dropna=False))
    print()

genome_type
Unknown    41
RNA        19
DNA         7
rna         1
RNA         1
Rna         1
Name: count, dtype: int64

strand
Unknown            41
ssRNA(+)           10
ssRNA(-)            8
dsDNA               7
partially dsDNA     1
ssRNA-RT            1
dsRNA               1
ssRNA               1
Name: count, dtype: int64

enveloped
NaN      41
True     25
False     4
Name: count, dtype: int64

transmission
vector           22
bodily fluids    15
contact          15
airborne         14
Airborne          1
animal bite       1
vectorr           1
air borne         1
Name: count, dtype: int64

In [21]:
for var in ['host', 'family', 'genus']:
    print(dataset_full[var].value_counts(dropna=False))
    print()

host
both      25
animal    20
human     19
NaN        6
Name: count, dtype: int64

family
Unknown             39
NaN                  7
Flaviviridae         3
Herpesviridae        3
Poxviridae           2
Coronaviridae        2
Filoviridae          2
Retroviridae         1
Orthomyxoviridae     1
Hepadnaviridae       1
Rhabdoviridae        1
Caliciviridae        1
Papillomaviridae     1
Adenoviridae         1
Reoviridae           1
Paramyxoviridae      1
Hantaviridae         1
Arenaviridae         1
Pneumoviridae        1
Name: count, dtype: int64

genus
Unknown                41
NaN                     4
Betacoronavirus         3
Flavivirus              3
Orthopoxvirus           2
Simplexvirus            2
Lentivirus              1
Ebolavirus              1
Lyssavirus              1
Alphacoronavirus        1
Orthohepadnavirus       1
Mastadenovirus          1
Alphapapillomavirus     1
Marburgvirus            1
Rotavirus               1
Norovirus               1
Mammarenavirus          1
Orthopneumovirus        1
Orthorubulavirus        1
Morbillivirus           1
Varicellovirus          1
Name: count, dtype: int64

In [22]:
print(dataset_full['transmission'].value_counts(dropna=False))

transmission
vector           22
bodily fluids    15
contact          15
airborne         14
Airborne          1
animal bite       1
vectorr           1
air borne         1
Name: count, dtype: int64

In [23]:
print(dataset_full['genus'].value_counts(dropna=False))

genus
Unknown                41
NaN                     4
Betacoronavirus         3
Flavivirus              3
Orthopoxvirus           2
Simplexvirus            2
Lentivirus              1
Ebolavirus              1
Lyssavirus              1
Alphacoronavirus        1
Orthohepadnavirus       1
Mastadenovirus          1
Alphapapillomavirus     1
Marburgvirus            1
Rotavirus               1
Norovirus               1
Mammarenavirus          1
Orthopneumovirus        1
Orthorubulavirus        1
Morbillivirus           1
Varicellovirus          1
Name: count, dtype: int64

In [24]:
unknowns = dataset_full['genome_type'] == 'Unknown'
dataset_full.loc[unknowns, ['genome_type', 'strand', 'genus', 'enveloped', 'family']]

   genome_type   strand    genus enveloped   family
29     Unknown  Unknown  Unknown       NaN  Unknown
30     Unknown  Unknown  Unknown       NaN  Unknown
31     Unknown  Unknown  Unknown       NaN  Unknown
32     Unknown  Unknown  Unknown       NaN  Unknown
33     Unknown  Unknown  Unknown       NaN  Unknown
34     Unknown  Unknown  Unknown       NaN  Unknown
35     Unknown  Unknown  Unknown       NaN  Unknown
36     Unknown  Unknown  Unknown       NaN  Unknown
37     Unknown  Unknown  Unknown       NaN  Unknown
38     Unknown  Unknown  Unknown       NaN  Unknown
39     Unknown  Unknown  Unknown       NaN  Unknown
40     Unknown  Unknown  Unknown       NaN  Unknown
41     Unknown  Unknown  Unknown       NaN  Unknown
42     Unknown  Unknown  Unknown       NaN  Unknown
43     Unknown  Unknown  Unknown       NaN  Unknown
44     Unknown  Unknown  Unknown       NaN  Unknown
45     Unknown  Unknown  Unknown       NaN  Unknown
46     Unknown  Unknown  Unknown       NaN  Unknown
47     Unknown  Unknown  Unknown       NaN  Unknown
48     Unknown  Unknown  Unknown       NaN  Unknown
49     Unknown  Unknown  Unknown       NaN      NaN
50     Unknown  Unknown  Unknown       NaN  Unknown
51     Unknown  Unknown  Unknown       NaN  Unknown
52     Unknown  Unknown  Unknown       NaN  Unknown
53     Unknown  Unknown  Unknown       NaN  Unknown
54     Unknown  Unknown  Unknown       NaN      NaN
55     Unknown  Unknown  Unknown       NaN  Unknown
56     Unknown  Unknown  Unknown       NaN  Unknown
57     Unknown  Unknown  Unknown       NaN  Unknown
58     Unknown  Unknown  Unknown       NaN  Unknown
59     Unknown  Unknown  Unknown       NaN  Unknown
60     Unknown  Unknown  Unknown       NaN  Unknown
61     Unknown  Unknown  Unknown       NaN  Unknown
62     Unknown  Unknown  Unknown       NaN  Unknown
63     Unknown  Unknown  Unknown       NaN  Unknown
64     Unknown  Unknown  Unknown       NaN  Unknown
65     Unknown  Unknown  Unknown       NaN  Unknown
66     Unknown  Unknown  Unknown       NaN  Unknown
67     Unknown  Unknown  Unknown       NaN  Unknown
68     Unknown  Unknown  Unknown       NaN  Unknown
69     Unknown  Unknown  Unknown       NaN  Unknown

O dataset_full tem 70 linhas e 12 colunas. Rodei describe, isnull, dtypes e nunique e encontrei os seguintes pontos:
- Nulos: enveloped (41), family (7), host (6), genus (4), mortality (3). O target não tem nulos.
- Valores improváveis: mortality vai de -5 a 150. Como o dicionário define a variável como percentual de óbitos, a faixa válida que irei considerar é de 0 a 100.
- Tipos: o dicionário diz que enveloped deveria ser booleano (True/False), mas está como object por causa dos nulos.
- Padronização: genome_type tem 6 valores únicos, mas o dicionário diz que deve ter apenas RNA ou DNA. Podemos ver que existem valores escritos de formas diferentes, precisamos padronizar. O mesmo acontece em transmission, que tem typos como "Airborne", "air borne" e "vectorr".
- Mistura de Unknown e NaN: family e genus têm tanto "Unknown" quanto NaN convivendo, são duas formas diferentes de representar a mesma coisa e precisam ser unificadas.
- O valor "Unknown" aparece em 41 linhas em genome_type, strand e genus, e enveloped tem 41 NaN. Confirmei que são as mesmas 41 linhas, ou seja, um bloco de vírus sem caracterização biológica. Vou manter esses registros e tratar "Unknown" como categoria válida, descartar significaria perder 58% da base e imputar inventaria informação.
- Nomes: name tem 70 valores únicos em 70 linhas, assim como o ID não há como enriquecer o modelo com essa feature portanto será removida